### ISSUE TITLE
[ Feature Request ] Searching directories recursively

### ISSUE THREAD

**Issue by hringriin** [damienlangg/SimpleMovieCatalog#11]
I cannot see a solution to have a dir like `/home/max/movies` searched recursively, meaning folders like `MadMax` or `Die Hard` in `/home/max/movies` are ignored.

**Comment by damienlangg** [comment]
Directories are always searched recursively. If some movies are not recognized it must be a different reason for that, to make sure a movie is found either include the year of release in the dir name or file name or add a link to the movie on imdb to a title.nfo file

**Comment by hringriin** [comment]
Well, then I probably do not get how SMC works.

My directory looks like somewhat like this:

```
/home/<user>/media:

├── Movies
│   ├── The Avengers
│   │   ├── The Avengers.mkv
│   │   ├── Bonus
│   │   │   ├── Bonus 1.mkv
.   .   .   .
├── Series
│   ├── Navy CIS
│   │   ├── Season 01
│   │   │   ├── NCIS - s01e01 - Yankee White.mkv
│   │   │   ├── NCIS - s01e02 - Hung Out To Dry.mkv
.   .   .   .
```

Scanning the directory `/home/<user>/media` does not work.

**Comment by damienlangg** [comment]
from README:

The directories are scanned for: *.nfo, *.txt, *.url, *.desktop files that
contain links to imdb info like this: http://www.imdb.com/title/tt0062622/

If no such link is present then the movie title and year is guessed from
directory or file name and searched on imdb for an exact match.

If none of the above methods produce valid info, then the directory is
reported in the "Missing Info" group.

You can then resolve missing info for these directories by using one of
the following methods:

 - Find the movie on imdb and then drag&drop the link from your
   browser location bar to the directory containing the movie.
   This will create a .url file (.desktop on linux) in that directory.

 **- To make guessing work better rename the directory to use the format:
   "Title (Year) [optional additional info]"
   Guessing will only use Title and Year. Year is mandatory and anything
   following year is ignored.**

 - Try playing with some options to relax the search:
        -**my (search also if missing year in dir or file name)**
        -mf (match first if multiple results)
        -aka (match AKA titles - in other language than original).
   The matching will not be so strict so you might get more hits,
   but the results might not be as accurate.

 - **Manually create a .nfo or .txt file in the directory and put
   the imdb link inside.**

**Comment by hringriin** [comment]
Thanks.
